### ISSUE TITLE
Change opacity of awakenings you have 0 of from .5 to .6

### ISSUE THREAD

**Issue by RheingoldRiver** [TsubakiBotPad/teambuilder#46]
ss of .6

![image](https://user-images.githubusercontent.com/18037011/209549806-a74a812b-5d89-4f20-8e07-2134af716b26.png)

**Comment by tarunsamanta2k20** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by RheingoldRiver** [comment]
https://github.com/TsubakiBotPad/teambuilder/blob/master/src/components/teamStats/awakenings.tsx#L238
