### ISSUE TITLE
Negotiate a standard format for teaming data exchange

### ISSUE THREAD

**Issue by Mapaler** [TsubakiBotPad/teambuilder#83]
Hello, I am the developer of [PAD Dash Formation](https://github.com/Mapaler/PADDashFormation).
Now each team editor has its own data format, which makes it inconvenient for users to replace the team they see shared by others with their favorite team builder.
I hope to have a community discussion to form a standardized, extensible (with advanced functions of different builders) and easy-to-handle (JSON format) data structure.

### APP
* [PDC パズドラダメージ計算](https://play.google.com/store/apps/details?id=com.corombo13.paddamagecal) Export and import in QR code. Because it is the earliest team builder and probably the most widely used, it is currently the most compatible with PDC format.
* [PADDB](https://play.google.com/store/apps/details?id=com.bj.paddb) At present, it uses links to share JSON, but because of CSP restrictions, it is difficult to obtain content through front-end web pages. So it should also be difficult to import from other team builder.   
  To import the team sharing link of PADDB, you need to use a back-end program to obtain the JSON code of team data.  
  `curl -X POST -H "Content-Type:application/json" -H "Content-Length:33" -H "Host:api2.paddb.net" -H "Connection:Keep-Alive" -H "Accept-Encoding:gzip" -H "User-Agent:okhttp/4.9.2" -d "{\"id\":\"63b287659b239a72f6cc79b1\"}" "https://api2.paddb.net/getTeam"`
* [PAD Builder](https://play.google.com/store/apps/details?id=com.elfwill.padb) No data sharing method found.
### WEB
* [Valeria](https://github.com/mtkwock/Valeria/)  Use a format called pdchu. But this project is relatively unpopular, and Valeria itself has not been active for a long time.
* [PAD Index](https://pad.chesterip.cc/team-builder/) Use PDC QR code to share, no import function found.
* [PAD Dash Formation](https://github.com/Mapaler/PADDashFormation) Support the import and export of PDC format and own data format. (own format is poor. I'm considering abandoning it)
* [tsubakibot/ PAD Team Builder](https://teambuilder.tsubakibot.com) Private format that is difficult to parse.

**Comment by RheingoldRiver** [comment]
Thanks for reaching out! We do actually plan on having an import-export format (See #40), and we will be using pdchu, as that's the format Tsubaki Bot uses. However, this is pretty far down in our backlog. In the meantime, we'd love to have you join our discord [(link)](https://discord.gg/QCRxNtC) where there's a channel for the teambuilder app!

**Comment by Mapaler** [comment]
> we will be using pdchu, as that's the format Tsubaki Bot uses

Where can I get documentation or code samples in PDCHU format?

**Comment by RheingoldRiver** [comment]
Type `^helpbuildimg` from any server Tsubaki is in, or [here's the code that implements it](https://github.com/TsubakiBotPad/pad-cogs/blob/master/padbuildimg/padbuildimg.py)

**Comment by RheingoldRiver** [comment]
(btw once you output pdchu format, people will be able to import your builds into Tsubaki too, which is the original reason for us doing it)

**Comment by Mapaler** [comment]
I see PDCHU format, need to use a name string to specify the card and latent, which I don't think is migrable to other languages and backwards compatible.
A map corresponding to the card name (abbreviation) and ID needs to be maintained that is constantly updated, and the newly added latent needs to wait for the name before it can be used.
If I export a PDCHU that names the card with an abbreviation used by Chinese(小椿) or Japanese(ツバキ), I'm sure you won't be able to handle it either.

**Comment by Mapaler** [comment]
![1674909537517_firefox](https://user-images.githubusercontent.com/6565860/215266847-d9080509-b883-40b6-a178-507e792f96ab.png)
And this bug occurs when entering a character whose Japanese ID is inconsistent with the English ID.
